### PR TITLE
Cast translate PL

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rsiebert** [comment]
There are new strings that needs to be translated. So I'll wait.
Also check that you don't break the formatting / indentation. 89 strings didn't change but you have removed the spaces in front of them.

**Comment by ghost** [comment]
Ok i correct it. But i dont see any new strings to translate ...

**Comment by rsiebert** [comment]
Forgot to push the changes. Here you go...

**Comment by pepeEL** [comment]
What forgot ? I dont understand... :(

**Comment by rsiebert** [comment]
I forgot to add my changes to github.

**Comment by ghost** [comment]
Ok thanks DONE

**Pull request merged**
