### PR TITLE
Next small update PL

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rsiebert** [comment]
I have updated some arrays. You do not need to translate arrays that are marked with translatable=false

**Comment by ghost** [comment]
ok thanks

But i think that this:

string-array name="pref_language_list_display" translatable="false"
-        <item>Domylny</item>
-        <item>Niemiecki</item>
-        <item>Angielski</item>
-        <item>Francuzki</item>
-        <item>Włoski</item>
-        <item>Holenderski</item>
-        <item>Polski</item>
-        <item>Szwedzki</item>
-        <item>Czeski</item>
-        <item>Hiszpański</item>
-    </string-array>

should be translate...

**Comment by rsiebert** [comment]
I have added the array for the polish language.

**Comment by ghost** [comment]
ok thanks

**Pull request closed without merging**
